---
- name: Deploy NGINX Plus
  hosts: aws_ec2
  become: true
  remote_user: "{{ hostvars[inventory_hostname]['tags']['user'] }}"
  collections:
    - nginxinc.nginx_core
  roles:
    - role: nginx
      vars:
        nginx_type: plus
        nginx_license:
          certificate: <path/to/cert>
          key: <path/to/key>
        nginx_remove_license: false
