---
- hosts: aws_ec2
  become: true
  remote_user: "{{ hostvars[inventory_hostname].tags.user }}"
  collections:
    - nginxinc.nginx_core
  roles:
    - role: nginx_config
      vars:
        nginx_config_http_template_enable: true
        nginx_config_http_template:
          - template_file: http/default.conf.j2
            deployment_location: /etc/nginx/conf.d/default.conf
            config:
              servers:
                - core:
                    listen:
                      - port: 80
                    server_name: localhost
                  log:
                    access:
                      - path: /var/log/nginx/access.log
                        format: main
                  sub_filter:
                    sub_filters:
                      - string: server_hostname
                        replacement: $hostname
                      - string: server_address
                        replacement: $server_addr:$server_port
                      - string: server_url
                        replacement: $request_uri
                      - string: remote_addr
                        replacement: '$remote_addr:$remote_port'
                      - string: server_date
                        replacement: $time_local
                      - string: client_browser
                        replacement: $http_user_agent
                      - string: request_id
                        replacement: $request_id
                      - string: nginx_version
                        replacement: $nginx_version
                      - string: document_root
                        replacement: $document_root
                      - string: proxied_for_ip
                        replacement: $http_x_forwarded_for
                  locations:
                    - location: /
                      core:
                        index: index.html
                        root: /usr/share/nginx/html

        nginx_config_html_demo_template_enable: true
        nginx_config_html_demo_template:
          - template_file: www/index.html.j2
            deployment_location: /usr/share/nginx/html/index.html
            web_server_name: Ansible NGINX collection
