---
- name: Deploy an NGINX Plus reverse proxy load balancing between two NGINX Plus web servers protected by NGINX App Protect
  hosts: aws_ec2
  become: true
  remote_user: "{{ hostvars[inventory_hostname]['tags']['user'] }}"
  roles:
    - role: nginxinc.nginx_core.nginx_app_protect
      vars:
        nginx_app_protect_setup_license: false
        nginx_app_protect_remove_license: false
        nginx_app_protect_install_signatures: true
        nginx_app_protect_install_threat_campaigns: true
    - role: nginxinc.nginx_config
      vars:
        nginx_config_modules:
          - modules/ngx_http_app_protect_module.so
        nginx_config_http_template_enable: true
        nginx_config_http_template:
          - template_file: http/default.conf.j2
            deployment_location: /etc/nginx/conf.d/default.conf
            config:
              servers:
                - core:
                    listen:
                      - port: 80
                    server_name: localhost
                  app_protect_waf:
                    enable: true
                    policy_file: /etc/app_protect/conf/NginxDefaultPolicy.json
                    security_log_enable: true
                    security_log:
                      path: /etc/app_protect/conf/log_default.json
                      dest: /var/log/app_protect/security.log
                  log:
                    access:
                      - path: /var/log/nginx/access.log
                        format: main
                  locations:
                    - location: /
                      proxy:
                        pass: http://upstr/
                        set_header:
                          field: Host
                          value: $host
                - core:
                    listen:
                      - port: 8008
                    server_name: localhost
                  log:
                    access:
                      - path: /var/log/nginx/access.log
                        format: main
                  sub_filter:
                    sub_filters:
                      - string: server_hostname
                        replacement: $hostname
                      - string: server_address
                        replacement: $server_addr:$server_port
                      - string: server_url
                        replacement: $request_uri
                      - string: remote_addr
                        replacement: '$remote_addr:$remote_port'
                      - string: server_date
                        replacement: $time_local
                      - string: client_browser
                        replacement: $http_user_agent
                      - string: request_id
                        replacement: $request_id
                      - string: nginx_version
                        replacement: $nginx_version
                      - string: document_root
                        replacement: $document_root
                      - string: proxied_for_ip
                        replacement: $http_x_forwarded_for
                  locations:
                    - location: /
                      core:
                        index: server_one.html
                        root: /usr/share/nginx/html
                - core:
                    listen:
                      - port: 8009
                    server_name: localhost
                  log:
                    access:
                      - path: /var/log/nginx/access.log
                        format: main
                  sub_filter:
                    sub_filters:
                      - string: server_hostname
                        replacement: $hostname
                      - string: server_address
                        replacement: $server_addr:$server_port
                      - string: server_url
                        replacement: $request_uri
                      - string: remote_addr
                        replacement: '$remote_addr:$remote_port'
                      - string: server_date
                        replacement: $time_local
                      - string: client_browser
                        replacement: $http_user_agent
                      - string: request_id
                        replacement: $request_id
                      - string: nginx_version
                        replacement: $nginx_version
                      - string: document_root
                        replacement: $document_root
                      - string: proxied_for_ip
                        replacement: $http_x_forwarded_for
                  locations:
                    - location: /
                      core:
                        index: server_two.html
                        root: /usr/share/nginx/html
              upstreams:
                - name: upstr
                  least_conn: true
                  servers:
                    - address: 0.0.0.0:8008
                    - address: 0.0.0.0:8009


        nginx_config_html_demo_template_enable: true
        nginx_config_html_demo_template:
          - template_file: www/index.html.j2
            deployment_location: /usr/share/nginx/html/server_one.html
            web_server_name: Ansible NGINX collection - Server one
          - template_file: www/index.html.j2
            deployment_location: /usr/share/nginx/html/server_two.html
            web_server_name: Ansible NGINX collection - Server two
